// build.gradle
plugins {
    id 'java'
    id 'xyz.jpenilla.run-paper' version '3.0.2'
}

group = 'plugins.ppi'
version = '1.0.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.+'
    compileOnly 'io.netty:netty-handler:4.1.118.Final'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks {
    runServer {
        minecraftVersion('26.1.2')
        jvmArgs('-Dcom.mojang.eula.agree=true')
        standardInput = System.in
    }
}
